{"name": "Логин курьера с невалидными данными", "status": "passed", "description": "Проверка ошибки при попытке логина курьера с невалидными данными", "start": 1701117504185, "stop": 1701117504483, "uuid": "9ee9cd34-3a4f-4345-895e-0fe6130ba41b", "historyId": "a54c79da6778e67a082486dae24636bd", "testCaseId": "a54c79da6778e67a082486dae24636bd", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_with_invalid_credentionals", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-C4ER3HN"}, {"name": "thread", "value": "19640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}